// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_signup_duplicate', function() {
  this.timeout(100000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_signup_duplicate', async function() {
    await driver.get("http://localhost:3001/activations")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    await driver.findElement(By.css(".AppBar__menu-item")).click()
    await driver.findElement(By.css(".LoginDialog__title--clickable")).click()
    await driver.findElement(By.css(".Tabs > div > button:nth-child(1) > div")).click()
    await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div/div/input")).sendKeys("123asdqwezxc@outlook.com")
    await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div[2]/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div[2]/div/input")).sendKeys("test1")
    await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div[2]/div/div/button/div")).click()
    await driver.wait(until.elementLocated(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div/div/div[3]")), 30000)
    assert(await driver.findElement(By.xpath("//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/form/div/div/div/div[3]")).getText() == "User with this e-mail address has been already registered")
  })
})


describe('clickaround', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('clickaround', async function() {
    await driver.get("http://localhost:3001/activations")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    await driver.findElement(By.css(".mdl-card:nth-child(1) > .QuizCard__media")).click()
    await driver.findElement(By.css(".AppBar__left .material-icons")).click()
    await driver.findElement(By.css(".mdl-card:nth-child(2) > .QuizCard__media")).click()
    await driver.findElement(By.css(".AppBar__left .material-icons")).click()
    await driver.findElement(By.css(".mdl-card:nth-child(3) > .QuizCard__media")).click()
    await driver.findElement(By.css(".AppBar__left .material-icons")).click()
    await driver.findElement(By.css(".mdl-card:nth-child(4) > .QuizCard__media")).click()
    await driver.findElement(By.css(".AppBar__left .material-icons")).click()
    await driver.findElement(By.css(".mdl-card:nth-child(5) > .QuizCard__media")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".AppBar__left > .mdl-button")).click()
    await driver.findElement(By.css(".mdl-card:nth-child(6) > .QuizCard__media")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".AppBar__left .material-icons")).click()
    await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[4]/div/div/div/div[7]/div[3]")).click()
    await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[4]/div/div/div/div[7]/div[2]")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[3]/div/div[2]/button/i")).click()
    // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[4]/div/div/div/div[8]/div[2]")).click()
    // await driver.executeScript("window.scrollTo(0,0)")
    // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[3]/div/div[2]/button/i")).click()
    // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[3]/div[2]/div/div/div/a[2]/span[2]")).click()
    // // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[4]/div/div/div/div[3]/div[2]")).click()
    // await driver.findElement(By.xpath("//div[@id=\'app-view\']/div/div/div/div[3]/div/div[2]/button/i")).click()
    await driver.close()
  })
})
