# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest;
import string
import random
class TestPostquiz(unittest.TestCase):
  def setUp(self):
    chrome_options = webdriver.ChromeOptions()
    prefs = {"profile.default_content_setting_values.notifications" : 2}
    chrome_options.add_experimental_option("prefs",prefs)
    self.driver = webdriver.Chrome("drivers/chromedriver",chrome_options=chrome_options)
    self.vars = {}
  
  def tearDown(self):
    self.driver.close()
  
  def test_postquiz(self):
    self.driver.get("http://localhost:3001/activations")
    self.driver.set_window_size(1600, 900)
    self.driver.find_element(By.CSS_SELECTOR, ".AppBar__menu-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".LoginDialog__title--clickable").click()
    # time.sleep(2)
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div[2]/form/div/div/div/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div[2]/form/div/div/div/input").send_keys("zhilinw3@illinois.edu")
    # time.sleep(2)
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div[2]/form/div/div[2]/div/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div[2]/form/div/div[2]/div/input").send_keys("password")
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div[2]/form/div[2]/div/div/button/div/div/span").click()
    time.sleep(10)
    # WebDriverWait(self.driver, 300000).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id='content']/div/div/div/div/div[3]/div/div[2]/div[2]/span/div/div/a")))
    self.driver.find_element(By.CSS_SELECTOR, ".ListItem > div > div:nth-child(2)").click()
    self.driver.find_element(By.XPATH, "//div[4]/div/div/div[2]/div/button/div/div/span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".CodeMirror-line").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > textarea:nth-child(1)").send_keys("123")
    self.driver.find_element(By.ID, "option-0").click()
    self.driver.find_element(By.ID, "option-0").send_keys("1")
    self.driver.find_element(By.ID, "option-1").click()
    self.driver.find_element(By.ID, "option-1").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, ".Select-placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Select-input > input").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".Select-input > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".FlatButton:nth-child(2) > button > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".profile-picture").click()
    self.driver.find_element(By.CSS_SELECTOR, ".RaisedButton:nth-child(2) div > div > span").click()
  
if __name__ == '__main__':
  unittest.main()